# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ee126710c31bc90011c815d30b7e0a91b791fd9d5023644f9bdbb602ca54080378a85a5d37e20bd973df2d28c637cefac90a7d9a18eca8dbc1111041168c77

test:
  secret_key_base: 9c37a175fca5c9379372da0bf5b8d8e84c76d42b2ddab77305ab07d53f17872e0d1d5c3be43b1f918e15ce7693f35b903fad34443a34706a67abd197a3ea1b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
